language: python
python:
  - "2.7"
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  aapp: floating-mountain-66927
  api_key: 8074099b-4548-482c-aac7-85a31a08cefd
