language: python
python:
  - "2.7"

install:
  - make deps

script:
  - make test

lint:
  - make lint

after_success:
  - make docker_build
  - make docker_push

language: python
services:
  - docker
