language: python
python:
  - "2.7"
services:
  - docker
install:
  - make deps
script:
  - make test
  - make lint
  - make docker_build
  - make docker_run
  - sleep 2; python test-api/api.py
after_success:
  - make docker_push

deploy:
  provider: heroku
  app: floating-mountain-66927
  api_key: ${HEROKU_API_KEY}
